### ISSUE TITLE
Dx Uncaught translation error

### ISSUE THREAD

**Issue by sol4ris2048** [Hipmob/gifanimateddrawable#13]
Hello,

Thanks for your work on this lib

After generating .jar with build.xml and ant, i add this generated jar to my project.

But i have this 4 errors below...
Could you help me?

Thanks a lot! 

The 4 errors : 
Dx Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/hipmob/gifanimationdrawable/GifAnimationDrawable$1;
Dx Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/hipmob/gifanimationdrawable/GifAnimationDrawable;
Dx Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/hipmob/gifanimationdrawable/GifDecoder$GifFrame;
Dx Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/hipmob/gifanimationdrawable/GifDecoder;

**Comment by fomojola** [comment]
Not sure if this is still an issue (I'm guessing not!) but this was probably because the classes were being added twice somehow.
